apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-frontend
  labels:
    app: microservice-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-frontend
  template:
    metadata:
      labels:
        app: microservice-frontend
    spec:
      containers:
        - name: microservice-frontend
          image: jtan22/microservice-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: jdbc:mysql://host.docker.internal/petclinic
            - name: VET_SERVICE_URL
              value: http://microservice-vet:8080/vets
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: microservice-frontend